title: Kento Miyazawa
description: Portfolio, CV, and blog in Japanese and English
url: "https://miyaken1201.github.io"
baseurl: ""
locale: ja
timezone: Asia/Tokyo

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed

markdown: kramdown
permalink: /:categories/:title/
post_pagination: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      share: false
      related: false
      sidebar:
        nav: "nav_ja"

include:
  - _pages
